spring:
  profiles:
    active: dev
  application:
    name: dataline-boot
  mvc:
    favicon:
      enable: false;

server:
  port: 80
  tomcat:
    max-threads: 400
    uri-encoding: UTF-8

#logging:
#  level:
#    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG


mybatis:
  configuration:
    aggressiveLazyLoading: false
    lazyLoadingEnabled: true
    lazyLoadTriggerMethods: ""
    mapUnderscoreToCamelCase: true

logging:
  path: "../hyacinth-logs/prod"
  level:
    root: info
    org.springframework.web: debug

jdbc:
  jdbcUrl: jdbc:mysql://localhost:3306/hyacinth_db?useUnicode=true&characterEncoding=utf8
  username: root
  password: 12345678

baseUrl:
  baiduBaseUrl: https://www.baidu.com/
